### PR TITLE
Feature/publish styling

### PR DESCRIPTION
**Pull request by gfodor**
- Turns back on mosaic titles + tweaks docs in light of that
- Styling pass on login flow
- Slightly better model loading error messages from Sketchfab + Poly

### CODE REVIEW

**Comment by gfodor** [comment]
no need for a deep review, one q i had is if the break out of the UI flow into `import.js` is the way you'd do it.

**Comment by brianpeiris** [comment]
Since AddNodeActionButtons is a child of ViewportPanelContainer, I would just expose `onURLEntered` as a property of AddNodeActionButtons and have a handler in ViewportPanelContainer. That way you don't have to split it out to import.js

**Comment by brianpeiris** [comment]
LGTM otherwise

**Comment by gfodor** [comment]
I renamed it to `wasModified` but then realized the logic was off for the load file case. I refactored in (and landed it on master) to be `isDefaultScene`, and its `true` iff the scene is an unmodified default scene. (Which is what I wanted anyway)

**Comment by brianpeiris** [comment]
:+1: much clearer now

**Pull request merged**
